[project]
name = "cc-sandbox"
version = "0.1.0"
description = "Claude Code Action sandbox project"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "langchain",
    "langchain-openai", 
    "langgraph"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"